jed pre0.99-19 changes 101-102 101. lib/html.sl: If _Reserved_Key_Prefix is NULL, do not use if in      calls to un/definekey. 102. Updated aclocal.m4 for better CYGWIN support
git-svn-id: svn+ssh://svn.gna.org/svn/jed/trunk@70 d7b853f0-af0c-0410-a2ac-8624e5f26e42

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -686,9 +686,13 @@ CC_SHARED
 ELFLIB
 ELFLIB_MAJOR
 ELFLIB_MAJOR_MINOR
+ELFLIB_MAJOR_MINOR_MICRO
 SLANG_LIB_FOR_MODULES
 DLL_IMPLIB_NAME
 INSTALL_MODULE
+INSTALL_ELFLIB_TARGET
+ELFLIB_BUILD_NAME
+SLANG_DLL_CFLAGS
 XMKMF
 X_CFLAGS
 X_PRE_LIBS
@@ -4179,9 +4183,6 @@ fi
 
 
 
-ELFLIB="lib\$(THIS_LIB).so"
-ELFLIB_MAJOR="\$(ELFLIB).\$(ELF_MAJOR_VERSION)"
-ELFLIB_MAJOR_MINOR="\$(ELFLIB).\$(ELF_MAJOR_VERSION).\$(ELF_MINOR_VERSION)"
 
 if test "$GCC" = yes
 then
@@ -4191,7 +4192,15 @@ then
   fi
 fi
 
+ELFLIB="lib\$(THIS_LIB).so"
+ELFLIB_MAJOR="\$(ELFLIB).\$(ELF_MAJOR_VERSION)"
+ELFLIB_MAJOR_MINOR="\$(ELFLIB_MAJOR).\$(ELF_MINOR_VERSION)"
+ELFLIB_MAJOR_MINOR_MICRO="\$(ELFLIB_MAJOR_MINOR).\$(ELF_MICRO_VERSION)"
+
+INSTALL_ELFLIB_TARGET="install-elf-and-links"
+ELFLIB_BUILD_NAME="\$(ELFLIB_MAJOR_MINOR_MICRO)"
 INSTALL_MODULE="\$(INSTALL_DATA)"
+SLANG_DLL_CFLAGS=""
 
 case "$host_os" in
   *linux*|*gnu*|k*bsd*-gnu )
@@ -4271,29 +4280,38 @@ case "$host_os" in
      ELFLIB="lib\$(THIS_LIB).dylib"
      ELFLIB_MAJOR="lib\$(THIS_LIB).\$(ELF_MAJOR_VERSION).dylib"
      ELFLIB_MAJOR_MINOR="lib\$(THIS_LIB).\$(ELF_MAJOR_VERSION).\$(ELF_MINOR_VERSION).dylib"
+     ELFLIB_MAJOR_MINOR_MICRO="lib\$(THIS_LIB).\$(ELF_MAJOR_VERSION).\$(ELF_MINOR_VERSION).\$(ELF_MICRO_VERSION).dylib"
      ;;
   *freebsd* )
-    ELFLIB_MAJOR_MINOR="\$(ELFLIB).\$(ELF_MAJOR_VERSION)"
     ELF_CC="\$(CC)"
     ELF_CFLAGS="\$(CFLAGS) -fPIC"
-    if test "X$PORTOBJFORMAT" = "Xelf" ; then
-      ELF_LINK="\$(CC) \$(LDFLAGS) -shared -Wl,-soname,\$(ELFLIB_MAJOR)"
-    else
-      ELF_LINK="ld -Bshareable -x"
-    fi
+    #if test "X$PORTOBJFORMAT" = "Xelf" ; then
+    #  ELF_LINK="\$(CC) \$(LDFLAGS) -shared -Wl,-soname,\$(ELFLIB_MAJOR)"
+    #else
+    #  ELF_LINK="ld -Bshareable -x"
+    #fi
+    ELF_LINK="\$(CC) \$(LDFLAGS) -shared -Wl,-soname,\$(ELFLIB_MAJOR)"
     ELF_DEP_LIBS="\$(DL_LIB) -lm"
     CC_SHARED="\$(CC) \$(CFLAGS) -shared -fPIC"
     ;;
   *cygwin* )
     DYNAMIC_LINK_FLAGS=""
     ELF_CC="\$(CC)"
-    ELF_CFLAGS="\$(CFLAGS) "
+    SLANG_DLL_CFLAGS="-DSLANG_DLL=1"
+    ELF_CFLAGS="\$(CFLAGS) -DBUILD_DLL=1"
     DLL_IMPLIB_NAME="lib\$(THIS_LIB)\$(ELFLIB_MAJOR_VERSION).dll.a"
-    ELF_LINK="\$(CC) \$(LDFLAGS) -shared -Wl,-O1 -Wl,--version-script,\$(VERSION_SCRIPT) -Wl,-soname,\$(ELFLIB_MAJOR) -Wl,--out-implib=\$(DLL_IMPLIB_NAME) -Wl,-export-all-symbols -Wl,-enable-auto-import"
+    #ELF_LINK="\$(CC) \$(LDFLAGS) -shared -Wl,-O1 -Wl,--version-script,\$(VERSION_SCRIPT) -Wl,-soname,\$(ELFLIB_MAJOR) -Wl,--out-implib=\$(DLL_IMPLIB_NAME) -Wl,-export-all-symbols -Wl,-enable-auto-import"
+    ELF_LINK="\$(CC) \$(LDFLAGS) -shared -Wl,-O1 -Wl,--version-script,\$(VERSION_SCRIPT) -Wl,-soname,\$(ELFLIB_MAJOR) -Wl,--out-implib=\$(DLL_IMPLIB_NAME)"
     ELF_DEP_LIBS="\$(DL_LIB) -lm"
-    CC_SHARED="\$(CC) \$(CFLAGS) -shared"
+    CC_SHARED="\$(CC) \$(CFLAGS) -shared -DSLANG_DLL=1"
         SLANG_LIB_FOR_MODULES="-L\$(ELFDIR) -lslang"
     INSTALL_MODULE="\$(INSTALL)"
+    INSTALL_ELFLIB_TARGET="install-elf-cygwin"
+    ELFLIB="lib\$(THIS_LIB).dll"
+    ELFLIB_MAJOR="lib\$(THIS_LIB)\$(ELF_MAJOR_VERSION).dll"
+    ELFLIB_MAJOR_MINOR="lib\$(THIS_LIB)\$(ELF_MAJOR_VERSION)_\$(ELF_MINOR_VERSION).dll"
+    ELFLIB_MAJOR_MINOR_MICRO="lib\$(THIS_LIB)\$(ELF_MAJOR_VERSION)_\$(ELF_MINOR_VERSION)_\$(ELF_MICRO_VERSION).dll"
+    ELFLIB_BUILD_NAME="\$(ELFLIB_MAJOR)"
     ;;
   * )
     echo "Note: ELF compiler for host_os=$host_os may be wrong"
@@ -4303,6 +4321,10 @@ case "$host_os" in
     ELF_DEP_LIBS="\$(DL_LIB) -lm -lc"
     CC_SHARED="\$(CC) \$(CFLAGS) -shared -fPIC"
 esac
+
+
+
+
 
 
 
@@ -6690,13 +6712,30 @@ echo "$as_me: error: --with-slanginc requres a value" >&2;}
   	  /opt/lib/slang \
   	  /opt/slang/lib"
 
+       case "$host_os" in
+         *darwin* )
+	   exts="dylib so a"
+	   ;;
+	 * )
+	   exts="so a"
+       esac
+
+       found=0
        for X in $lib_library_dirs
        do
-        if test -r "$X/libslang.so" -o -r "$X/libslang.a"
-  	then
-  	  jd_slang_library_dir="$X"
-	  break
-        fi
+         for E in $exts
+	 do
+           if test -r "$X/libslang.$E"
+	   then
+  	     jd_slang_library_dir="$X"
+	     found=1
+	     break
+           fi
+         done
+	 if test $found -eq 1
+	 then
+	   break
+	 fi
        done
        if test X"$jd_slang_library_dir" = X
        then
@@ -6745,6 +6784,12 @@ case "$host_os" in
       RPATH="-Wl,-rpath,"
     else
       RPATH="-rpath "
+    fi
+  ;;
+  *netbsd*)
+    if test "X$GCC" = Xyes
+    then
+      RPATH="-Wl,-R"
     fi
   ;;
 esac
@@ -7544,9 +7589,13 @@ CC_SHARED!$CC_SHARED$ac_delim
 ELFLIB!$ELFLIB$ac_delim
 ELFLIB_MAJOR!$ELFLIB_MAJOR$ac_delim
 ELFLIB_MAJOR_MINOR!$ELFLIB_MAJOR_MINOR$ac_delim
+ELFLIB_MAJOR_MINOR_MICRO!$ELFLIB_MAJOR_MINOR_MICRO$ac_delim
 SLANG_LIB_FOR_MODULES!$SLANG_LIB_FOR_MODULES$ac_delim
 DLL_IMPLIB_NAME!$DLL_IMPLIB_NAME$ac_delim
 INSTALL_MODULE!$INSTALL_MODULE$ac_delim
+INSTALL_ELFLIB_TARGET!$INSTALL_ELFLIB_TARGET$ac_delim
+ELFLIB_BUILD_NAME!$ELFLIB_BUILD_NAME$ac_delim
+SLANG_DLL_CFLAGS!$SLANG_DLL_CFLAGS$ac_delim
 XMKMF!$XMKMF$ac_delim
 X_CFLAGS!$X_CFLAGS$ac_delim
 X_PRE_LIBS!$X_PRE_LIBS$ac_delim
@@ -7564,12 +7613,9 @@ PROGRAM_OFILES!$PROGRAM_OFILES$ac_delim
 PROGRAM_CFILES!$PROGRAM_CFILES$ac_delim
 PROGRAM_HFILES!$PROGRAM_HFILES$ac_delim
 PROGRAM_OBJECTS!$PROGRAM_OBJECTS$ac_delim
-PROGRAM_ELFOBJECTS!$PROGRAM_ELFOBJECTS$ac_delim
-LIBOBJS!$LIBOBJS$ac_delim
-LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 96; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -7601,6 +7647,52 @@ N; s/^.*\n//; s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g; b n
 ' >>$CONFIG_STATUS <conf$$subs.sed
 rm -f conf$$subs.sed
 cat >>$CONFIG_STATUS <<_ACEOF
+CEOF$ac_eof
+_ACEOF
+
+
+ac_delim='%!_!# '
+for ac_last_try in false false false false false :; do
+  cat >conf$$subs.sed <<_ACEOF
+PROGRAM_ELFOBJECTS!$PROGRAM_ELFOBJECTS$ac_delim
+LIBOBJS!$LIBOBJS$ac_delim
+LTLIBOBJS!$LTLIBOBJS$ac_delim
+_ACEOF
+
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 3; then
+    break
+  elif $ac_last_try; then
+    { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
+echo "$as_me: error: could not make $CONFIG_STATUS" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    ac_delim="$ac_delim!$ac_delim _$ac_delim!! "
+  fi
+done
+
+ac_eof=`sed -n '/^CEOF[0-9]*$/s/CEOF/0/p' conf$$subs.sed`
+if test -n "$ac_eof"; then
+  ac_eof=`echo "$ac_eof" | sort -nru | sed 1q`
+  ac_eof=`expr $ac_eof + 1`
+fi
+
+cat >>$CONFIG_STATUS <<_ACEOF
+cat >"\$tmp/subs-2.sed" <<\CEOF$ac_eof
+/@[a-zA-Z_][a-zA-Z_0-9]*@/!b end
+_ACEOF
+sed '
+s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g
+s/^/s,@/; s/!/@,|#_!!_#|/
+:n
+t n
+s/'"$ac_delim"'$/,g/; t
+s/$/\\/; p
+N; s/^.*\n//; s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g; b n
+' >>$CONFIG_STATUS <conf$$subs.sed
+rm -f conf$$subs.sed
+cat >>$CONFIG_STATUS <<_ACEOF
+:end
+s/|#_!!_#|//g
 CEOF$ac_eof
 _ACEOF
 
@@ -7848,7 +7940,7 @@ s&@abs_builddir@&$ac_abs_builddir&;t t
 s&@abs_top_builddir@&$ac_abs_top_builddir&;t t
 s&@INSTALL@&$ac_INSTALL&;t t
 $ac_datarootdir_hack
-" $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed 's/|#_!!_#|//g' >$tmp/out
+" $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed -f "$tmp/subs-2.sed" >$tmp/out
 
 test -z "$ac_datarootdir_hack$ac_datarootdir_seen" &&
   { ac_out=`sed -n '/\${datarootdir}/p' "$tmp/out"`; test -n "$ac_out"; } &&
